### ISSUE TITLE
local-web-server is missed in package.json

### ISSUE THREAD

**Issue by adyshev** [outsrc/monorepo#1]
STR:
1. fresh install
2. yarn start
3. pm2 logs template

Output: 
https://www.dropbox.com/s/jokjyl1q55odtn1/Screenshot%202021-01-09%20at%2018.59.11.png?dl=0

OS:
OSX Big Sur

Proposed solution to make initial idea working:
Add local-web-server into package.json, "dependencies" section

Question:
Do you think ws is ok for prod use? And why don't you use 'next build && next start' for this instead? 

Thanks!

**Comment by ernestofreyreg** [comment]
`ws` is not good for prod use. 

I guess I was not explicit enough about the way I prefer to build and deploy Nextjs applications. For my use cases building an SSG (via `next export`) is always the preferred way. If you need SSR then yes, `next build && next start` should be the way to go. My purpose with `ws` is to build the static app and serve it as a regular CDN would do.

Will add `local-web-server` to dependencies for sure.

**Comment by ernestofreyreg** [comment]
Added `local-web-server`

**Comment by adyshev** [comment]
> `ws` is not good for prod use.
> 
> I guess I was not explicit enough about the way I prefer to build and deploy Nextjs applications. For my use cases building an SSG (via `next export`) is always the preferred way. If you need SSR then yes, `next build && next start` should be the way to go. My purpose with `ws` is to build the static app and serve it as a regular CDN would do.
> 
> Will add `local-web-server` to dependencies for sure.

Got it. Thank you, Sir!
